name: Deploy Supabase Edge Functions

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # actions/checkout v4.2.2 のフルSHAに固定
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b

      - name: Install Supabase CLI
        run: |
          curl -fsSL https://github.com/supabase/cli/releases/latest/download/supabase_linux_amd64.tar.gz \
            | sudo tar -xz -C /usr/local/bin supabase
          supabase --version

      - name: Login (non-TTY safe)
        run: supabase login --token "${{ secrets.SUPABASE_ACCESS_TOKEN }}"

      - name: Link project
        run: supabase link --project-ref "${{ secrets.SUPABASE_PROJECT_ID }}"

      - name: Set Secrets (optional)
        run: |
          if [ -n "${{ secrets.GN_HOST_PIN }}" ]; then
            supabase secrets set GN_HOST_PIN="${{ secrets.GN_HOST_PIN }}"
          fi

      - name: Deploy sessions-advance
        run: supabase functions deploy sessions-advance
